name: gestor_academico
description: "Gestor Académico Inteligente"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.8 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Selector de archivos
  file_picker: ^8.1.2

  # Lectura de CSV
  csv: ^6.0.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2

  # Navegación
  go_router: ^13.2.0

  # Generar QR
  qr_flutter: ^4.1.0

  # Estado
  provider: ^6.1.2

  # Escanear QR
  mobile_scanner: ^5.2.3

  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true