// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEcOt4vLZkR7ny7Iq4vprLPYsZc5I7s-Q',
    appId: '1:773085841218:web:5d029e4ca06adbdc876adb',
    messagingSenderId: '773085841218',
    projectId: 'gestor-academico-ff7f6',
    authDomain: 'gestor-academico-ff7f6.firebaseapp.com',
    storageBucket: 'gestor-academico-ff7f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6aQmYexUia-lqW54ecBt6JpVROcKQg-U',
    appId: '1:773085841218:android:17c9fe4d6ccb2973876adb',
    messagingSenderId: '773085841218',
    projectId: 'gestor-academico-ff7f6',
    storageBucket: 'gestor-academico-ff7f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNhbXRW3Q753AUP6f5XpJPZZzBnyxl3_I',
    appId: '1:773085841218:ios:2c7720ad7bf9f41d876adb',
    messagingSenderId: '773085841218',
    projectId: 'gestor-academico-ff7f6',
    storageBucket: 'gestor-academico-ff7f6.firebasestorage.app',
    iosBundleId: 'com.example.gestorAcademico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNhbXRW3Q753AUP6f5XpJPZZzBnyxl3_I',
    appId: '1:773085841218:ios:2c7720ad7bf9f41d876adb',
    messagingSenderId: '773085841218',
    projectId: 'gestor-academico-ff7f6',
    storageBucket: 'gestor-academico-ff7f6.firebasestorage.app',
    iosBundleId: 'com.example.gestorAcademico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEcOt4vLZkR7ny7Iq4vprLPYsZc5I7s-Q',
    appId: '1:773085841218:web:287c5fc4145cc776876adb',
    messagingSenderId: '773085841218',
    projectId: 'gestor-academico-ff7f6',
    authDomain: 'gestor-academico-ff7f6.firebaseapp.com',
    storageBucket: 'gestor-academico-ff7f6.firebasestorage.app',
  );
}
